apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gestionar-data
  namespace: gestionar
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
